version: '3.7'

volumes:
    logs:
        driver: local

services:
    nginx:
        image: $IMAGE_NGINX
        container_name: gabaev-template-backend-slim-4
        volumes:
            - ../../:/app
            - ../../infra/images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 127.0.8.1:80:80
        depends_on:
            - app
    app:
        build: ../images/php-fpm
        container_name: gabaev-template-backend-slim-4-app
        env_file: .env
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ../../:/app
            - ../../infra/images/php-fpm/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini:ro
        working_dir: '/app/'
networks:
    default:
        external:
            name: bqgid